*     List of files to be included in the CASE2 model
*     Be carefull about changing path indicators

      INCLUDE 'C:\FSE\MODULES\ASTRSKY\SASTRO\1.1\SASTRO.FOR'
*      INCLUDE 'C:\FSE\MODULES\CROPS\NOCROP.FOR'
      INCLUDE 'C:\FSE\MODULES\DRIVERS\2.1m\FSE.FOR'
*      INCLUDE 'C:\FSE\MODULES\EVAPO\PENMAN\1.1\SETPMD.FOR'
*      INCLUDE 'C:\FSE\MODULES\EVAPO\PENMAN\1.1\setpmd2.FOR'
      INCLUDE 'C:\FSE\MODULES\EVAPO\MAKKINK\1.0\SETMKD.FOR'
      INCLUDE 'C:\FSE\MODULES\EVAPO\PTAYLOR\1.0\SETPTD.FOR'
      INCLUDE 'C:\FSE\MODULES\EVAPO\VPS\SVPS1\1.0\SVPS1.FOR'
      INCLUDE 'C:\FSE\MODULES\WATBAL\DRPOT\DRPOT.FOR'
      INCLUDE 'C:\FSE\MODULES\WATBAL\DRSAHE\1.5\DRSAHE.FOR'
      INCLUDE 'C:\FSE\MODULES\WATBAL\SWSE\1.1\SWSE.FOR'
      INCLUDE 'C:\FSE\MODULES\WEATHER\METEO\1.1\METEO.FOR'
      INCLUDE 'C:\FSE\MODULES\WEATHER\CLIMRD\1.2\CLIMRD.FOR'
      INCLUDE 'C:\FSE\MODULES\WEATHER\RNREAL\RNREAL.FOR'
      INCLUDE 'C:\FSE\MODULES\WEATHER\RNGEN\RNGEN.FOR'
      INCLUDE 'C:\FSE\MODULES\WEATHER\RNDIS\RNDIS.FOR'
      INCLUDE 'C:\FSE\MODULES\WEATHER\AFGEN.FOR' 
      INCLUDE 'C:\FSE\MODULES\WEATHER\GAMMA2.FOR' 
      INCLUDE 'C:\FSE\MODULES\WEATHER\RANDOM.FOR' 
*      INCLUDE 'C:\FSE\CACAO\CASE2\2.1\LIESJE\TOTASC.FOR'
      INCLUDE 'C:\fse\libs\ttutil\wread.for' !added by PAZ 4-5-2001